appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: E4Tp5WcCx7DWNoFdzA+boL2MGKEqxV3VgoFAXptX0RMFM5cCIJhp/1xKRg/atXAu6zxhuZOGLt0qG/cF2SCCuGnO22HDVqvSXvgKRWveMfLEL2+KmYYWIk7eH6Yek7IZcsqB8C1swoc515m+nzCvKn42ukTf4LDFubNjEIReYGkQUW1LQXGu9Q168Y76Neqlsec8LIpU5MyPd9YHCJrjlsx2zikMOjFG+Pkau10SBSABMpJgU49vdPoGBR0sBzWnxSs3snQ0ZHhRFfkh7C+1His3QUf0iYJEksGWfE9CFMs0mViHQ8Ul+4yMCBJ8Jfa6SuJUnapQAwOV7brmfZiNM7pLC1gwd1ID1Qdc6brLGJzCYBL7pOWzGH07ejtFkQK3lONy9jJlMzVcomXulYxiJb350ZZYJUBV0OEtgcL8T65HnenZ6O5pbiQjqTJqud7abe/7AlvAtrlFja/Tr4nKIml9hVoP2n8yroy5xlN4AbTUgZbFyUKdk5TzfGrh8e03ExjPAzPgbTsOY690TfEsgvDK1+bb+N1nbGIF2S0Vxy7aIB4kvY9RfDzty/zcbQuwgw6s0Dn/PbUgmryxLzb10m6nvKu9oXLSt8vpUpnqu8FA0aPcGQfT00wc5ALo9EOh/qJEpO87qG3HnPJcBJfO/8V6xRd9tpy9EQxIqr2NZbY=}
